
name: colorful_notes_app
description: A simple colorful notes app
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.9.0

flutter:
  uses-material-design: true
